# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

EXPOSE 8080

LABEL 	io.openshift.tags="apache, httpd" \
	io.k8s.display-name="Apache Http Server" \
	io.openshift.expose-services="8080:http" \
	io.k8s.description="A basic Apache HTTP Server child image"

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
	sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf && \
	chgrp -R 0 /var/log/httpd /var/run/httpd && \
	chmod -R u=g /var/log/httpd /var/run/httpd

USER 1001
